# Generated by Django 5.1.4 on 2026-06-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='idle_timeout_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
