# Generated by Django 5.1.4 on 2026-05-31 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_type', models.CharField(choices=[('DEDICATED', 'Dedicated'), ('SHARED', 'Shared')], default='SHARED', max_length=20)),
                ('allocation_percentage', models.PositiveIntegerField(default=100, help_text="Share of this person's time, 0-100")),
                ('bill_rate', models.DecimalField(blank=True, decimal_places=2, help_text='What the client is charged per hour', max_digits=10, null=True)),
                ('cost_rate', models.DecimalField(blank=True, decimal_places=2, help_text='What this person costs the firm per hour', max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'user_id'],
            },
        ),
    ]
