# Generated by Django 5.1.4 on 2026-06-01 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField()),
                ('app', models.CharField(blank=True, max_length=255)),
                ('window_title', models.CharField(blank=True, max_length=512)),
                ('active', models.BooleanField(default=True)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_samples', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['organization', 'user', 'captured_at'], name='monitoring__organiz_07513b_idx')],
            },
        ),
    ]
