# Generated by Django 5.1.4 on 2026-06-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
        ('timetracking', '0003_timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='activity_type',
            field=models.CharField(choices=[('WORK', 'Project work'), ('BREAK', 'Break'), ('INTERNAL_MEETING', 'Internal meeting'), ('CLIENT_MEETING', 'Client meeting')], default='WORK', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='projects.project'),
        ),
    ]
